### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by stuaxo** [stuaxo/vext#1]
Make it work in python 3

**Comment by stuaxo** [comment]
Probably have to use importlib.machinery in place of imp.

**Comment by rutsky** [comment]
Any progress on this issue?

**Comment by stuaxo** [comment]
Not really, but will make it a higher priority, it would involve having an alternate implementation to the 

GateKeeperLoader and GateKeeperFinder -

https://github.com/stuaxo/vext/blob/master/vext/__init__.py#L143

using importlib.machinery instead + then just choose the right implementation depending on python version.

Going to move to more py3 dev pretty soon, so will probably update it then.

**Comment by stuaxo** [comment]
Work started on py3 branch https://github.com/stuaxo/vext/tree/py3  - no py3 support yet.

**Comment by stuaxo** [comment]
Seems to be working enough to import PyQt5.QtGui (and the Qt4 versions).

Can't import sip, also gi.repository doesn't work from vext.gi

**Comment by andreubotella** [comment]
As I mentioned on #23, vext.gi and the rest of packages don't install on Python 3 because the `print` call in line 37 is missing parentheses.

**Comment by stuaxo** [comment]
Doh, was in hotel room + assumed this was in the merge, will have time to sort it out + test in next few hours when I get back/

**Comment by stuaxo** [comment]
Updated and uploaded to pypi - now works for me (TM) on python 3   for  vext.gi, vext.pyqt4, vext.pyqt5  I _think_ that most of the others don't have python3 packages (?).

**Comment by stuaxo** [comment]
Closing ... looks like things will need rewriting in python 3.6, but will have a new ticket if 3.6 happens and imp is removed.
