### ISSUE TITLE
Add vext.pyqt5

### ISSUE THREAD

**Issue by rutsky** [stuaxo/vext#18]
I tried to it myself, but looks like even vext.pyqt4 is broken: #17

**Comment by stuaxo** [comment]
Have you got the .vext file ?   I can test it here on python2..

**Comment by rutsky** [comment]
I just replaced 4 with 5 in pyqt4.vext, e.g.:

```
# Pyqt5 vext
#

# Vext will allow access to these modules
modules:
    pyqt5
    PyQt5
    sip

test_import:
    # Vext will try and import any modules here
    # To check if the install worked
    pyqt5, sip, PyQt5

install_hints:
    PyQt5 was not found, install it in your system python.
```

Where vext-files are hosted?

**Comment by stuaxo** [comment]
Cool, for now I'm just hosting the source on github + uploading a seperate project to pypi for each one supported (hopefully won't be too many).

I've added a Qt5, but I'm not sure it works with python3 bindings on Ubuntu, so might be a bit stuck without py3 support.

I've made a new release with PyQt5, and the start of support for install_hints - so at least there will be a message when things can't install.

**Comment by stuaxo** [comment]
vext files are installed to  share/vext/specs  inside 'sys.prefix'  this can be something like

'/mnt/data/home/stu/.virtualenvs/my_virtualenv/share/vext/specs'

**Comment by stuaxo** [comment]
Any idea how I use pyqt5 on Ubuntu, (not in virtualenv or vext) -

I've tried installing pyqt5-dev pyqt5-examples and python3-pyqt5 from apt-get  but can't seem to import pyqt5 using the examples in /usr/share/doc/pyqt5-examples/examples/ any ideas ?

I'm on Ubuntu 15.10

**Comment by stuaxo** [comment]
Just seems to not find PyQt5

```
$ python lighting.py 
Traceback (most recent call last):
  File "lighting.py", line 47, in <module>
    from PyQt5.QtCore import QPointF, Qt, QTimer
ImportError: No module named PyQt5.QtCore
```

**Comment by stuaxo** [comment]
OK, found out how to do this via  ... SIP ...

**Comment by rutsky** [comment]
On Ubuntu 14.04 you need to install `python3-pyqt5` package. Notice that they have different packages for Python 2 and 3, and for PyQt4 and PyQt5.

```
$ python3 
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtCore import QPointF, Qt, QTimer
>>> 
```

**Comment by rutsky** [comment]
Not sure about 15.10, but in 14.04 default `python` is Python 2, to use Python 3 you need to run `python3`.

**Comment by stuaxo** [comment]
Do I need to use update-alternatives to make it available in py2 - currently it's just setup for PyQt4

**Comment by rutsky** [comment]
> Do I need to use update-alternatives to make it available in py2 - currently it's just setup for PyQt4

No, you don't need  to do update-alternatives.

Python 2 and 3 works in Ubuntu in parallel.
To use specific version of Python you can run `python2` or `python3` instead of simply `python`.

To install PyQt4 and PyQt5 for Python2 and Python3 you need to install following packages: `python-pyqt5 python-qt4 python3-pyqt5 python3-pyqt4`.

Here, I tested this in docker:

```
# docker pull ubuntu:15.10
15.10: Pulling from library/ubuntu
Digest: sha256:a8b34ad24519e34943976b402fd95e427ab233d3067c2b6405f455ca7afd9114
Status: Image is up to date for ubuntu:15.10
# docker run -ti --rm ubuntu:15.10 /bin/bash                                                                                       
root@0327c4a21726:/# apt-get update -q
Get:1 http://archive.ubuntu.com wily InRelease [218 kB]
Get:2 http://archive.ubuntu.com wily-updates InRelease [64.4 kB]
Get:3 http://archive.ubuntu.com wily-security InRelease [64.4 kB]
Get:4 http://archive.ubuntu.com wily/main Sources [1411 kB]
Get:5 http://archive.ubuntu.com wily/restricted Sources [7171 B]
Get:6 http://archive.ubuntu.com wily/universe Sources [8976 kB]
Get:7 http://archive.ubuntu.com wily/main amd64 Packages [1833 kB]
Get:8 http://archive.ubuntu.com wily/restricted amd64 Packages [23.1 kB]
Get:9 http://archive.ubuntu.com wily/universe amd64 Packages [8673 kB]
Get:10 http://archive.ubuntu.com wily-updates/main Sources [30.9 kB]
Get:11 http://archive.ubuntu.com wily-updates/restricted Sources [3560 B]
Get:12 http://archive.ubuntu.com wily-updates/universe Sources [6154 B]
Get:13 http://archive.ubuntu.com wily-updates/main amd64 Packages [94.4 kB]
Get:14 http://archive.ubuntu.com wily-updates/restricted amd64 Packages [20.4 kB]
Get:15 http://archive.ubuntu.com wily-updates/universe amd64 Packages [39.9 kB]
Get:16 http://archive.ubuntu.com wily-security/main Sources [20.5 kB]
Get:17 http://archive.ubuntu.com wily-security/restricted Sources [2681 B]
Get:18 http://archive.ubuntu.com wily-security/universe Sources [4628 B]
Get:19 http://archive.ubuntu.com wily-security/main amd64 Packages [68.2 kB]
Get:20 http://archive.ubuntu.com wily-security/restricted amd64 Packages [17.4 kB]
Get:21 http://archive.ubuntu.com wily-security/universe amd64 Packages [30.5 kB]
Fetched 21.6 MB in 1min 50s (196 kB/s)
Reading package lists...
root@0327c4a21726:/# apt-cache policy python-pyqt5 python-qt4 python3-pyqt5 python3-pyqt4
python-pyqt5:
  Installed: (none)
  Candidate: 5.4.2+dfsg-1build3
  Version table:
     5.4.2+dfsg-1build3 0
        500 http://archive.ubuntu.com/ubuntu/ wily/universe amd64 Packages
python-qt4:
  Installed: (none)
  Candidate: 4.11.4+dfsg-1build3
  Version table:
     4.11.4+dfsg-1build3 0
        500 http://archive.ubuntu.com/ubuntu/ wily/main amd64 Packages
python3-pyqt5:
  Installed: (none)
  Candidate: 5.4.2+dfsg-1build3
  Version table:
     5.4.2+dfsg-1build3 0
        500 http://archive.ubuntu.com/ubuntu/ wily/universe amd64 Packages
python3-pyqt4:
  Installed: (none)
  Candidate: 4.11.4+dfsg-1build3
  Version table:
     4.11.4+dfsg-1build3 0
        500 http://archive.ubuntu.com/ubuntu/ wily/main amd64 Packages
root@0327c4a21726:/# apt-get install -q -y  python-pyqt5 python-qt4 python3-pyqt5 python3-pyqt4
...
root@0327c4a21726:/# python2 -V
Python 2.7.10
root@0327c4a21726:/# python3 -V
Python 3.4.3+
root@0327c4a21726:/# python2 -c "import PyQt4.QtGui;"
root@0327c4a21726:/# python2 -c "import PyQt5.QtGui;"
root@0327c4a21726:/# python3 -c "import PyQt5.QtGui;"
root@0327c4a21726:/# python3 -c "import PyQt4.QtGui;"
```

**Comment by stuaxo** [comment]
Good testing - I really need to setup some docker based testing, since when vext goes wrong there's potential to really bugger the python env (especially for users using sudo by accident).

Looks I've done a bunch of debugging under py3 and it looks like APIs I use are still there in 3.4, so this actually works :)

The bad news is, that it will break in py3.5 when they are removed.

I've updated vext and vext.pyqt5, try them in a fresh virtualenv and let me know if they work, it seems OK for me on Wily under python3 and python2 (at least it can import PyQt5.QtGUI)

**Comment by stuaxo** [comment]
Seems to be workng enough under Py2, Python3 still needs sip to import.
