### ISSUE TITLE
Search also elsewhere in the system sys.path

### ISSUE THREAD

**Issue by andreubotella** [stuaxo/vext#19]
When I tried checking out this tool, nothing seemed to work on my system. I tried gi, gtk, PyQt5 on Python 2.7 and 3.4, but I always got the typical `ImportError: No module named gi`. After a lot of puzzling and digging around in the code, I found that vext is only searching in the system `pip`'s install location (in my case `/usr/`**`lib`**`/pythonX.Y/site-packages`).

So why is this a problem? Because for some reason, all Python packages from my distro's (Fedora 23) repos happen to be installed in `/usr/`**`lib64`**`/pythonX.Y/site-packages`.

So I think vext should probably search everywhere in the system's `sys.path` that's not in the virtualenv's `sys.path`, not only in `pip`'s install location.

**Comment by stuaxo** [comment]
Can you see what the output of `import site; site.getsitepackages()` is ?

Vext incorrectly assumes just one sitepackages dir:

```
from vext import env
env.getsyssitepackages()
Out[4]: '/usr/lib/python2.7/dist-packages'
```

Whereas on my system this isn't quite right:

```
In [1]: import site; site.getsitepackages()
Out[1]: ['/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
```

I'll grab a vm of fedora and have a play.   Originally I did add everything from the sys.path, but now am trying to add just the minimal needed - it might make sense to revisit this, will have to have a think.

Python 3.4 needs more work to work generally, but py 2.7 should be working, so will try and fix.

**Comment by andreubotella** [comment]
```
>>> import site
>>> site.getsitepackages()
['/usr/lib64/python3.4/site-packages', '/usr/lib/python3.4/site-packages', '/usr/lib/site-python']
```

Same for 2.7.

**Comment by stuaxo** [comment]
K, I'll add in multiple site packages in the short term, and in the longer term move to vext adding all paths in systems sys.path, but gatekeeping them.

**Comment by stuaxo** [comment]
Hi,
   I got this working - though you need to do `pip install -U pip setuptools` in the virtualenv first.    So far I've only updated vext.gi  but will upload the rest of the packages fairly soon.

I'll try and have a look into the detection for earlier setuptools.

S

**Comment by stuaxo** [comment]
OK, fixed the other problems so should install with `pip install vext.pyqt4` etc.
If anything doesn't work, feel free to re-open this.
