### ISSUE TITLE
Implement CI - Integration tests

### ISSUE THREAD

**Issue by stuaxo** [stuaxo/vext#24]
With each of the vext packages, following should be tested with py2 + py3 (where relevant):

Attempt to install as root without dependencies:
- [ ] checks should fail + hints should display.
- [ ]  install should abort and revert if possible.

Attempt to install in virtualenv without dependencies:
- [ ] checks should fail + hints should display.
- [ ]  install should abort and revert if possible.

Attempt to install as root with dependencies installed
- [ ]  install should succeed, but vext should NOT activate (or be possible to activate)
- [ ]  test imports should pass

Attempt to install in virtualenv with dependencies installed
- [ ]  Install should succeed
- [ ]  Test imports should pass

**Comment by andreubotella** [comment]
Have you considered any particular CI solution? I've been looking into using [Travis](https://travis-ci.org), and its [build environments for Python](https://docs.travis-ci.com/user/languages/python) always use a virtualenv, so the third case would be easy to do, but the other two would need a more involved config – though I'm pretty sure they can be done.

By the way, shouldn't the CI also test that the installation in a virtualenv fails if the dependencies aren't installed?

**Comment by stuaxo** [comment]
Agreed, travis looks great, + we can work out the more involved config once something is working.

I didn't realise travis does OSX, that just leaves Windows, there's a similar service for which I've lost the link to right now.

PGI is another project that uses Gtk and tests on travis, it might be possible to adapt their .travis config to make a simple test for vext.gi to start with.
- good catch, added.

**Comment by andreubotella** [comment]
We're actually talking about two different things.

Using `language: python`, we can test automatically on a number of versions (say, 2.6, 2.7, 3.3 to 3.5 plus an often-updated 3.6 nightly), but only on Linux and in a virtualenv. It should be possible to break out of the virtualenv, but I wouldn't trust that `/usr/bin/python` (or `python3`) be the same version as in the virtualenv. Sure, we can test and find out _where_ are those versions, but of course that would be undocumented and subject to change.

On the other hand, using `language: generic` as PGI does, we could test outside a virtualenv (even switching into one if needed), in both Ubuntu and OSX, but we'd be using the versions of Python provided by the OS.

When you add the project, I'll make a PR with a couple tests just to see what version are the system Python installs, where's the original for the versions in the virtualenvs and so on.

**Comment by stuaxo** [comment]
Indeed - roughly: unit tests vs integration tests ...   - the integration tests (language: generic) would be useful, since some of the bugs I triggered in earlier versions of vext and setuptools were quite inconvenient (like leaking memory until the computer stops, or just breaking the system python).

We could install our own known versions of the system python + create virtualenvs from them (virtualenv -p /usr/local/python-2.8/bin/python).   
- possibly thats how travis works, it might be worth checking orig-prefix.txt in their own virtualenvs ?

I've added vext and all the vext.\* projects to travis - it's probably easiest to put initial tests into vext itself.

**Comment by andreubotella** [comment]
It seems that in practice, the Travis config file allows fewer environment combinations than I thought. For one thing, according to travis-ci/travis-yaml#67, Travis only allows testing in OSX for projects either written in Objective-C or manually approved by the admins. Also, a project can't have more than one language.

From the Travis build logs: the syspy of the build virtualenv is always `/opt/python/X.Y.Z/bin/python`, independent of the system packages, which are the default versions for Ubuntu Precise. I suppose for testing the vext.\* projects we could symlink e.g., `/opt/python/X.Y.Z/lib/pythonX.Y/site-packages/gi` to `/usr/lib/pythonX/dist-packages/gi`.

**Comment by stuaxo** [comment]
We can ask for manual approval on OSX once something is working.

It looks like `language: generic` and having our own script to create a virtualenv using the system python + run tests, is going to be the best option.

Something similar to this 'multi-os' verson, but we can just use it for different linux distros to start:

https://docs.travis-ci.com/user/multi-os/

Symlinking is probably worth avoiding, it's only guaranteed to work on the same exact version of python, + will move from distro to distro, which is just the start of the rabbit-hole.

**Comment by stuaxo** [comment]
I started a travis branch to experiment in + had a go with a language generic

https://github.com/stuaxo/vext/blob/travis/.travis.yml

 `--in-venv=1` is passed when the test is run in a virtualenv, so the value can be grabbed by tests.

The test matrix has python 2 (system + virtualenv) and python 3 (virtualenv only).

I removed python3.2 with system python, as I couldn't get the pip install/upgrade working there.

Let me know if it looks useful.

**Comment by stuaxo** [comment]
Initial integration tests are added, in the form of a bash script that is passed the env.

Currently there is an integration test for virtualenv, but not venv as that didn't work on the first go.

Probably a lot of the bash script could be ported to travis, but this works for now.

Closing, can open individual tickets for new issues.
