### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by gladson** [stuaxo/vext#34]
![cc79648c598550fbb86f13941bccb9a1](https://cloud.githubusercontent.com/assets/1013698/17271723/94a52700-5651-11e6-8c1d-454dbbf549ba.jpg)

**Comment by gladson** [comment]
Would it be this?

If this is the solution? excuse.

> In your virtualenv:
> 
> Make sure setuptools and pip are up to date:
> $ pip install -U setuptools pip
> 
> Install what you need in the system python, then install the corresponding package:
> 
> Gtk3:
> $ pip install vext.gi
> 
> Pygtk:
> $ pip install vext.pygtk
> 
> PyQt4
> $ pip install vext.pyqt4
> 
> Wx
> $ pip install vext.wx
> 
> Pygame
> $ pip install vext.pygame
> 
> Panda3D
> $ pip install vext.panda3d
> 
> There's a bunch of things I'd like to fix and it may be buggy - having said that I'd used it for a few > months with Gtk 2 and 3 and it's been fine.
> 
> To disable it:
> 
> $ vext -d
> 
> To re-enable:
> 
> $ vext -e
> 
> https://github.com/stuaxo/vext
> 
> Most of these packages use the old C Python API ... if they got ported to CFFI then hopefully vext can become obsolete!
> 
> Let me know if there are any packages I should add.

**Comment by stuaxo** [comment]
It looks like you did `pip vext.gi` when you need `pip install vext.gi`.   Let me know how it goes..
