### ISSUE TITLE
vext.gi fails in python3.5 with recent setuptools

### ISSUE THREAD

**Issue by stuaxo** [stuaxo/vext#35]
check_sysdeps fails when running install

Disabling the test_imports section gets file installed, but import still seems to fail.

**Comment by stuaxo** [comment]
_Think_ I must have been using venv, not virtualenv here, closing.

**Comment by stuaxo** [comment]
Problem seems to be install vext.\* packages from pypi.

gi.vext ends up in {site-packages]/vext.gi-0.5.20-py3.5.egg  so this needs a new mechanism / shared space so that vext can find the newly installed .vext files ... crawling the whole site-packages dir can't be good for performance thought.

**Comment by stuaxo** [comment]
More guessing 
- Could not reproduce on Ubuntu 16.04
  pygobject here was installed from apt-get
  
  > > > gi.**file**
  > > > /usr/lib/python3/dist-packages/gi/**init**.py
- Could repro on Raspbian Jessie
  This is the based on older debian - so worth trying in a native debian Jessie + see if it is reproducable there.
  pygobject was a custom build
  
  > > > gi.**file**
  > > > '/usr/lib/python2.7/dist-packages/gi/**init**.pyc'

**Comment by stuaxo** [comment]
Seems like this happens when using a virtualenvs pip from outside that virtualenv.
- vext's setup.py tries to do "pip ..." but can't find pip.

**Comment by lofidevops** [comment]
~~Is this the same issue?~~ [moved to https://github.com/stuaxo/vext/issues/47 ]

**Comment by stuaxo** [comment]
That's a different issue - feel free to open another ticket about it.

**Comment by stuaxo** [comment]
Closing this until I find out how to reproduce this properly.
