### ISSUE TITLE
Executing "python -mpip" in vext.gi ignores arguments given to original pip command

### ISSUE THREAD

**Issue by jonathanpallant** [stuaxo/vext#39]
I'm trying to install vext in an off-line environment. To do this, I vendor all the packages I need into a third_party folder and install using:

```
pip install --no-index --find-links=./third_party {args}"
```

vext.gi appears to be calling pip directly and so ignores the arguments and it then fails because it can't find the arguments.

**Comment by stuaxo** [comment]
It looks like the extra arguments need to be added here

https://github.com/stuaxo/vext.gi/blob/18b537b56d8e8ff6d7f8fb84447b1b47f8e99362/setup.py#L45

What's the exact command line you are trying to install it with ?

**Comment by thejpster** [comment]
```
pip install --no-index --find-links=./third_party my-internal-product.zip
```

The package vext.gi is listed our setup.py (along with a bunch of other stuff).

**Comment by jonathanpallant** [comment]
```
pip install --no-index --find-links=./third_party my-private-package.zip
```

Where vext.gi is listed in the setup.py for our package.

**Comment by stuaxo** [comment]
I'm not going to have any time to look at this immediately, however if you do find a way to get those params in (possibly sys.argv will just work - but this being pip + setuptools I don't know), then I will probably land a patch.

**Comment by achan1989** [comment]
I'm curious about the check on line 41 -- what is this for?

Also, how do you package vext.gi for distribution?  I find that if I try to do something like `python3 setup.py sdist` then setuptools just tries to install vext.gi as normal.

**Comment by stuaxo** [comment]
Re: line 41 - good catch, that looks like I have cut n pasted that from vext's setup.py, it doesn't need to exist here.   (in vext itself it is to stop vext dropping its PTH file outside a virtualenv if you accidentally run it with sudo)

It's worth opening a bug about install on sdist, IRCC it was introduced as a workaround for setuptools sandbox (which was evolving at the same time as vext).

We would need to add some travis tests to fix this, to check the different install scenarios + verify it is / is not installed in the correct ones.

Re: packaging - I use ```python setup.py sdist upload -r pypi``` on all the vext.gi, vext.qt4 etc.

The source organisation could be better here, all these packages are basically the same except the README + .vext file.

**Comment by stuaxo** [comment]
I had another look @ the line 41 check.

There is a dependency issue in that vext.gi need vext itself to install the .vext file.   

In early versions of the code it was possible to install vext in the system python + activate it, this would cause all kinds of havoc (well, just break the system python until you deleted vexts .pth file.).

I'm fairly sure that vext won't enable itself in the system python any more, so this check probably isn't needed.

I probably left it in, as the ways the system python broke if the vext loader was enabled in it were many and varied (since I use powerline prompt, it even broke my bash prompt).

**Comment by stuaxo** [comment]
Merged, cheers :)
