### ISSUE TITLE
cannot suppress warning

### ISSUE THREAD

**Issue by kalikaneko** [stuaxo/vext#40]
I have vext.pyqt5 installed in my virtualenv, and now I'm getting a warning on every call to a cli program in this virtualenv:
```
WARNING:vext:Could not add extra path: /usr/share/sip
```
how can I suppress the warning in a painless way? 
I tried to configure the logger, but I think because vext plays with the import system this output happens before setting up the logger. any help would be appreciated.

**Comment by stuaxo** [comment]
The default level should probably be errors, try this fix  https://github.com/stuaxo/vext/pull/41  (it's untested, so it might need tweaking)

**Comment by kalikaneko** [comment]
that does the trick, indeed :)
:+1:

**Comment by stuaxo** [comment]
Cheers for the report, fix will be in next version.
