### ISSUE TITLE
vext logger can cause unexpected behaviour in other modules which use logging

### ISSUE THREAD

**Issue by JSKenyon** [stuaxo/vext#43]
I ran into this issue whilst working on some code which requires vext.pyqt4. Every time I install vext.pyqt4, all my logging output  disappears. I finally managed to track down the problem and figured that it might be possible to fix the problem/help someone else who runs into this.

vext.pyqt4 seems to instantiate an environment-wide logger. By this, I mean that there will be an active logger prior to any imports. This can be seen by starting a python shell and running:

```
import logging
print logging.Logger.manager.loggerDict
```

The problem with this is that it means the vext logger configures the root logger and sets its log level to WARNING. Thus, any new loggers will adhere to the log level of the root logger and most logging will be suppressed. It is obviously possible to change the log level on the root logger, but that can cause vext to clutter up existing logging. I chose to solve this (perhaps not the best approach, but I was in need of an easy fix) by putting the following right at the top of my code:

```
if 'vext' in logging.Logger.manager.loggerDict.keys():
    for handler in logging.root.handlers:
        logging.root.removeHandler(handler)
    logging.getLogger('vext').setLevel(logging.WARNING)
```

This allows my code to set up the logger as expected while still allowing vext to log warning level messages. Hope this is vaguely helpful.

**Comment by stuaxo** [comment]
Thanks for the info - my free time is pretty minimal at the moment - any idea what vext should be doing ?

Here is where vext sets up it's logger -

https://github.com/stuaxo/vext/blob/master/vext/__init__.py

It looks like it should be a relatively straightforward fix, are you up for making doing a pull request ?

**Comment by JSKenyon** [comment]
I am not sure if my expertise is up to the task, but if I have some spare time I will take a look. My fix works for now, so the fire is out but I would be interested to know the correct way of dealing with cases like this.

Thanks for the response!

**Comment by stuaxo** [comment]
I don't have time to test try it myself at the moment, but  It'll probably be something like this -

Move these lines

```python
if environ.get("VEXT_DEBUG_LOG", "0") == "1":
    logging.basicConfig(level=logging.DEBUG)
else:
    logging.basicConfig(level=logging.ERROR)
```

Under the line

```
logger = logging.getLogger("vext")
```

And then instead of using ```logging.basicConfig``` use ```logger.setLevel(logging.WARNING)``` like in your code.



I might be wrong though :)

**Comment by anntzer** [comment]
I think that in the default case (i.e., unless VEXT_DEBUG_LOG is set), vext should not call basicConfig at all.  See https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library:
> Note: It is strongly advised that you do not add any handlers other than NullHandler to your library’s loggers. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements.

**Comment by stuaxo** [comment]
That all makes a lot of sense, here's a pull request - I'm not in front of the computer with vext on it, so let me know if it seems right -

Logger - don't call basicConfig. - https://github.com/stuaxo/vext/pull/45

**Comment by anntzer** [comment]
lgtm, thanks!

**Comment by stuaxo** [comment]
Merged, cheers :)

**Comment by anntzer** [comment]
New release any time soon? :-)
I noticed the issue because matplotlib recently started using the stdlib logger, and also benefits from being able to use vext(.gi).

**Comment by stuaxo** [comment]
Definitely, ping me again if it hasn't happened by the end of the weekend, quite a lot of real life getting in the way at the moment!

Mostly, I just need to grab my pypi details from another computer.

**Comment by stuaxo** [comment]
OK, vext 0.7.0 is up on pypi, let me know if it works.
