### ISSUE TITLE
vext breaks application logging

### ISSUE THREAD

**Issue by akhilman** [stuaxo/vext#46]
I'm using logger in my application. After installing vext all message becomes duplicated.
```
WARNING:vext:Could not add extra path: /usr/share/sip
INFO    Connectiong to redis password=**** port=6379 host=localhost db=0
INFO:slivoglot.core.redishub:Connectiong to redis password=**** port=6379 host=localhost db=0
```
First info message printed by my apllication's logger, second one by  vext's logger.

**Comment by akhilman** [comment]
Found workaround by overloading root logger's handlers in my application.
https://stackoverflow.com/questions/44186667/python-logging-duplicate-log-entries

**Comment by stuaxo** [comment]
Is this a bug in vext, or just python logging being a bit confusing? 

Any idea what vext would need to change? 

The log setup for vext is in vext/__init__.py

**Comment by akhilman** [comment]
@stuaxo seems like It is just python logging...
I think there is nothing to do, vext does job at module initialization time, not at application running time, so there is no way to setup logger in application before vext does.

**Comment by stuaxo** [comment]
OK, I'll close this for now.

Python logging is definitely confusing (well, I have found it confusing as a casual user).   If this comes up again maybe it's worth adding some more docs.

At least it's possible to turn it on and off by environment variable, let me know if more control would be useful.

**Comment by akhilman** [comment]
Same wired behavior with pytest's logging.
Vext doubles all pytest's output.

**Comment by stuaxo** [comment]
I free time is severely constrained these days.

Have a look at the logging setup here   https://github.com/stuaxo/vext/blob/master/vext/__init__.py


If you don't have VEXT_DEBUG set, I'm pretty sure vext output should just go to the NullHandler.

Very possible that something silly is happening in vext that could be fixed simply though.

**Comment by akhilman** [comment]
I think the problem is the logger also setups the default handler for root logger.
I have the idea to implement a proxy class for logger that will do nothing even do not call ``getLogger()`` if ``VEXT_DEBUG_LOG``  is not set.

**Comment by stuaxo** [comment]
Is your version the same as the one in git ?

It might be worth uninstalling vext, then clone the git repo.

If you install vext using

```python setup.py develop```

it'll run straight from the git repo and you can experiment with changes (obviously do this in a virtualenv you don't care about, since if vext breaks strange things can happen).

**Comment by akhilman** [comment]
My bad, I had pip's version. Git's one works fine.

**Comment by stuaxo** [comment]
OK, that's my bad, I need to do a release.

**Comment by stuaxo** [comment]
I'll take this as the feedback I needed that the fix works though, thanks :)
