### ISSUE TITLE
Issues with VEXT_ALLOWED_MODULES

### ISSUE THREAD

**Issue by anntzer** [stuaxo/vext#48]
From https://github.com/stuaxo/vext/blob/d5d591d59965f94b046c9c1ef356fd88ed4e92c2/vext/gatekeeper/__init__.py#L42
it appears that VEXT_ALLOWED_MODULES is intended to be a list of extra allowed modules (actually this suggests a nice alternative way to use vext where one just install vext but none of the vext.foo, and globally set the environment variable to whatever they want), but
1) it should be re.split, not re.search;
2) the example a bit above in the doc, at https://github.com/stuaxo/vext/blob/d5d591d59965f94b046c9c1ef356fd88ed4e92c2/vext/gatekeeper/__init__.py#L11
appears to be incorrect.

**Comment by stuaxo** [comment]
Cheers, that certainly seems correct on the doc front, I'll accept a PR to fix both of these.

**Comment by stuaxo** [comment]
Wish I'd re-found this ticket when I fixed this just now, could have saved some time.

0.7.1 includes this fix and the doc change.
