### ISSUE TITLE
Python 2.7: reload() broken for some modules

### ISSUE THREAD

**Issue by ThomasGerstenberg** [stuaxo/vext#50]
There are cases where calling `reload()` on a module fails with the exception `AttributeError: 'module' object has no attribute 'load_module'`

Environment:
Vext v0.7.0
Mac OSX 10.13.4
Python 2.7.14/15 (brew-installed)
Virtual Environment created with `virtualenv`

Minimum steps to reproduce:
1. Create and activate a new virtual environment for Python 2.7
1. `pip install vext`
1. `pip install protobuf` (example module that causes the issue)
1. `python -c "import google; reload(google)"`

Output:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'load_module'
```

I tracked down the issue to this line here: https://github.com/stuaxo/vext/blob/3e033c7e67eb18f03b8770fc5e5c7157c0d50c8a/vext/gatekeeper/__init__.py#L238
changing `return sys.modules[fullname]` to `return` fixes the issue, but I'm unsure if this is the proper solution.

**Comment by stuaxo** [comment]
Can you try adding ```print(sys.modules.get(fullname))``` the line before that and testing with reload ?

I reckon the line itself could probably be ```return sys.modules.get(fullname)```

I hadn't tested with reload, it seems like a good candidate for a unit test.

**Comment by stuaxo** [comment]
Hi @ThomasGerstenberg 
   I've made a possible fix in the PR above, can you let me know if it works ?

Cheers
Stuart

**Comment by stuaxo** [comment]
Merged to master, will release update when there is a release

**Comment by stuaxo** [comment]
0.7.1 released.
