### ISSUE TITLE
Not installing even though it says it did.

### ISSUE THREAD

**Issue by stephenmm** [stuaxo/vext#51]
(python3_venv2) > python3 -m pip install vext.gi
Collecting vext.gi
Requirement already satisfied: vext>=0.7.0 in /proj/workareas/python3_venv2/lib/python3.5/site-packages (from vext.gi) (0.7.0)
Requirement already satisfied: ruamel.yaml>=0.11.10 in /proj/workareas/python3_venv2/lib/python3.5/site-packages (from vext>=0.7.0->vext.gi) (0.15.44)
Installing collected packages: vext.gi
Successfully installed vext.gi-0.7.0

(python3_venv2) > vext -c gi
gi is not an installed vext file.

(python3_venv2) > python3 -c 'import gi'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'gi'

I have tried with a bunch of packages that all claim to be successful but can't use them (  vext.pygtk vext.glib vext.PyQt4 vext.PyQt5 vext.wx vext.vtk ). 

I am probably missing something simple here but I just don't get it. Any thoughts or advice would be appreciated.

ADDITIONAL INFO:

(python3_venv2) > which vext
/proj/workareas/python3_venv2/bin/vext

(python3_venv2) > python3
Python 3.5.0 (default, Nov  5 2015, 10:24:59)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vext
>>> vext.<tab>
vext.VEXT_DEBUG_LOG     vext.__dict__           vext.__file__           vext.__gt__(            vext.__loader__         vext.__new__(           vext.__reduce_ex__(     vext.__spec__           vext.environ            vext.install_importer(  vext.registry
vext.__cached__         vext.__dir__(           vext.__format__(        vext.__hash__(          vext.__lt__(            vext.__package__        vext.__repr__(          vext.__str__(           vext.gatekeeper         vext.join(              vext.vext_pth
vext.__class__(         vext.__doc__            vext.__ge__(            vext.__init__(          vext.__name__           vext.__path__           vext.__setattr__(       vext.__subclasshook__(  vext.get_python_lib(    vext.logger
vext.__delattr__(       vext.__eq__(            vext.__getattribute__(  vext.__le__(            vext.__ne__(            vext.__reduce__(        vext.__sizeof__(        vext.env                vext.helpers            vext.logging
>>> vext.

(python3_venv2) > python3 -m pip -V
pip 10.0.1 from /proj/workareas/python3_venv2/lib/python3.5/site-packages/pip (python 3.5)

(python3_venv2) > cd /proj/workareas/python3_venv2/lib/python3.5/site-packages/vext.gi-0.7.0.dist-info
(python3_venv2) >  grep '' *
INSTALLER:pip
METADATA:Metadata-Version: 2.1
METADATA:Name: vext.gi
METADATA:Version: 0.7.0
METADATA:Summary: Use system python packages in a virtualenv
METADATA:Home-page: https://github.com/stuaxo/vext
METADATA:Author: Stuart Axon
METADATA:Author-email: stuaxo2@yahoo.com
METADATA:License: MIT
METADATA:Keywords: virtualenv gi vext gtk
METADATA:Platform: UNKNOWN
METADATA:Classifier: Development Status :: 3 - Alpha
METADATA:Classifier: Intended Audience :: Developers
METADATA:Classifier: Topic :: Software Development :: Build Tools
METADATA:Classifier: License :: OSI Approved :: MIT License
METADATA:Classifier: Programming Language :: Python :: 2.7
METADATA:Classifier: Programming Language :: Python :: 3.4
METADATA:Requires-Dist: vext (>=0.7.0)
METADATA:
METADATA:
METADATA:Allow use of system gi.repository (Gtk3) from a virtualenv
METADATA:Should work on all platforms.
METADATA:
METADATA:report bugs to https://github.com/stuaxo/vext
METADATA:
METADATA:
pbr.json:{"is_release": false, "git_version": "2fd13d4"}
RECORD:../../../gi.vext,sha256=0pA2jdET0c87dUxQST8u2GDiCAwovYNE_Kl_5lnkUcA,445
RECORD:vext.gi-0.7.0.dist-info/METADATA,sha256=pMsPOUGyKsrrLEFaz0OpH4U7k16MGjy34QzaONe8K0M,727
RECORD:vext.gi-0.7.0.dist-info/RECORD,,
RECORD:vext.gi-0.7.0.dist-info/WHEEL,sha256=ej5K9kDyb2XL1BKIws31ue3caMRhWQVxP9FqiOBUudY,93
RECORD:vext.gi-0.7.0.dist-info/pbr.json,sha256=UdnGEGNZP-S3s3H8QDxiUf5KIVuf6tTXCoQKU0g7vjw,47
RECORD:vext.gi-0.7.0.dist-info/top_level.txt,sha256=AbpHGcgLb-kRsJGnwFEktk7uzpZOCcBY74-YBdrKVGs,1
RECORD:vext.gi-0.7.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
top_level.txt:
WHEEL:Wheel-Version: 1.0
WHEEL:Generator: bdist_wheel (0.31.1)
WHEEL:Root-Is-Purelib: true
WHEEL:Tag: cp35-none-any
WHEEL:

**Comment by stuaxo** [comment]
When you try and do "import gi" in your system python does that work ?

(Did you definitely install these libraries in the right system python - on windows it's easy to end up with multiple installs).

Is the system python exactly the same version as the one in the virtualenv - the virtualenv should be created from the system python that has the library in it you want to access.

**Comment by stephenmm** [comment]
Wow, my bad. I completely misunderstood what vext was doing. For some reason I though vext would allow you to install the libraries/packages that you did not have on the system. I will blame it on being late on a Friday.

**Comment by stuaxo** [comment]
If you have any ideas to make the README clearer they are welcome - PR implementing them even more so :)
