### ISSUE TITLE
Vext does not create share folder for gi

### ISSUE THREAD

**Issue by bluppfisk** [stuaxo/vext#52]
Trying to install gi doesn't work on my new clone of my code:

```
(cpi) sander@tuhao:~/code/cpi$ pip install vext.gi
Requirement already satisfied: vext.gi in ./lib/python3.6/site-packages (0.7.0)
Requirement already satisfied: vext>=0.7.0 in ./lib/python3.6/site-packages (from vext.gi) (0.7.0)
Requirement already satisfied: ruamel.yaml>=0.11.10 in ./lib/python3.6/site-packages (from vext>=0.7.0->vext.gi) (0.15.64)
(cpi) sander@tuhao:~/code/cpi$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sander/code/cpi/lib/python3.6/site-packages/vext/gatekeeper/__init__.py", line 204, in load_module
   raise ImportError("No module named %s" % modulename)
   ImportError: No module named gi
```

Funnily, on another installation, vext seems to have created a folder **share**

```
share
└── vext
    └── specs
        └── gi.vext
```

but this is not created when I just run `pip3 install vext vext.gi`

**Comment by bluppfisk** [comment]
never mind, I didn't understand that I needed to run `vext -i gi.vext` after pip'ing

**Comment by stuaxo** [comment]
Wellll.... I think that it probably should enable it installing vext.gi from pip.

Did you install vext.gi before or after gobject in the system python ?

**Comment by bluppfisk** [comment]
In both projects, system pygobject had already been installed before. In one case however, the **share** folder was there; in the other it wasn't.
