### ISSUE TITLE
`vext.pyqt5` doesn't work on ubuntu Ubuntu 18.04.2

### ISSUE THREAD

**Issue by wolfgang-noichl** [stuaxo/vext#58]
...with virtualenv from apt (15.1.0+ds-1.1). Oddly enough, it works with the same version of virtualenv on ubuntu 18.10. It _does_ work on 18.04.2 after `sudo pip install --upgrade virtualenv`.

I don't think this is much of a problem, but it would be nice if it was mentioned somewhere.

**Comment by stuaxo** [comment]
Hi,
   I'll accept a PR against vext.pyqt5.    Do you have some more info about the error?
At home I use Ubuntu 18.10, which isn't helpful for testing.

Cheers
Stuart

**Comment by stuaxo** [comment]
Closing as no new info, feel free to reopen if you can get some logs when you try and do the imports with the environment variables set:

VEXT_DEBUG_LOG=1
VEXT_LOG_BLOCKS=1
