### ISSUE TITLE
Enable/disable in help output is mixed up

### ISSUE THREAD

**Issue by NomAnor** [stuaxo/vext#71]
The descriptions for enable/disable are mixed up.

> usage: vext [-h] [-l] [-e] [-d] [-s] [-c [CHECK [CHECK ...]]] [-i [INSTALL [INSTALL ...]]]
> 
> Access system python modules from virtualenv.
> 
> optional arguments:
>   -h, --help            show this help message and exit
>   -l, --list            List installed external packages
>   -e, --enable          Disable Vext loader
>   -d, --disable         Enable Vext loader
>   -s, --status          Show Vext status
>   -c [CHECK [CHECK ...]], --check [CHECK [CHECK ...]]
>                         [external package] Test imports for external package
>   -i [INSTALL [INSTALL ...]], --install [INSTALL [INSTALL ...]]
>                         Install vext file (used during setup)
>

**Comment by stuaxo** [comment]
Oops!

Can you submit a PR ?
