### ISSUE TITLE
WARNING on python execution

### ISSUE THREAD

**Issue by Findus23** [stuaxo/vext#78]
Thanks for the great package, I think it will save me a lot of trouble using matplotlib with qt5 in a virtual env. 

This feels a lot like the other logging issues that have already been solved, but I am still experiencing the same on a fresh install of the latest version
```bash
➜  ~/tmp python3 -m venv test       
➜  ~/tmp ./test/bin/pip install vext.pyqt5
Collecting vext.pyqt5
  Downloading vext.pyqt5-0.7.4.tar.gz (7.8 kB)
Collecting vext>=0.7.4
  Downloading vext-0.7.4.tar.gz (16 kB)
Collecting ruamel.yaml>=0.11.10
  Using cached ruamel.yaml-0.16.12-py2.py3-none-any.whl (111 kB)
Using legacy setup.py install for vext.pyqt5, since package 'wheel' is not installed.
Using legacy setup.py install for vext, since package 'wheel' is not installed.
Installing collected packages: ruamel.yaml, vext, vext.pyqt5
    Running setup.py install for vext ... done
    Running setup.py install for vext.pyqt5 ... done
Successfully installed ruamel.yaml-0.16.12 vext-0.7.4 vext.pyqt5-0.7.4
➜  ~/tmp ./test/bin/python
WARNING:vext:Skipped adding nonexistant path: /usr/share/sip
Python 3.9.1+ (default, Feb  5 2021, 13:46:56) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

So on every start of Python `WARNING:vext:Skipped adding nonexistant path: /usr/share/sip` is logged (also in scripts that don't use python logging at all).

I am using python 3.9.1 on Debian testing. If you need any more information, just ask.

**Comment by stuaxo** [comment]
It does look like it.   I'm not sure when I'm going to get free time to look at this.

The logging setup is here
https://github.com/vext-python/vext/blob/master/vext/__init__.py

And the message is here
https://github.com/vext-python/vext/blob/ba0ca703a02b63fba5e4d4261cf9fc053dcafaa3/vext/gatekeeper/__init__.py#L355

It's worth cloning vext out from git and verifying it still occurs.

**Comment by stuaxo** [comment]
Possibly a silly question, but can you check you don't have the latest version and that none of the environment variables for debug are set ?

**Comment by Findus23** [comment]
How do I install the `vext.pyqt5` package from git?
```bash
./test/bin/pip install git+https://github.com/vext-python/vext.git
./test/bin/pip install git+https://github.com/stuaxo/vext.pyqt5.git
```
doesn't seem to work correctly (I can't import PyQt5 afterwards)
My environment variables don't seem to contain anything related to `VEXT_`.

**Comment by Findus23** [comment]
Okay, I'll have to look into this in more detail once I have more time:
```bash
➜  ~/tmp python3 -m venv test
➜  ~/tmp ./test/bin/python
Python 3.9.1+ (default, Feb  5 2021, 13:46:56) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5'
>>> 
➜  ~/tmp ./test/bin/pip install vext.pyqt5
Collecting vext.pyqt5
  Using cached vext.pyqt5-0.7.4.tar.gz (7.8 kB)
Processing /home/lukas/.cache/pip/wheels/75/fd/f6/14eff36448d7576e78cb86ba2b504bde54740da6bc104b4873/vext-0.7.4-py3-none-any.whl
Collecting ruamel.yaml>=0.11.10
  Using cached ruamel.yaml-0.16.12-py2.py3-none-any.whl (111 kB)
Using legacy setup.py install for vext.pyqt5, since package 'wheel' is not installed.
Installing collected packages: ruamel.yaml, vext, vext.pyqt5
    Running setup.py install for vext.pyqt5 ... done
Successfully installed ruamel.yaml-0.16.12 vext-0.7.4 vext.pyqt5-0.7.4
➜  ~/tmp ./test/bin/python                
Python 3.9.1+ (default, Feb  5 2021, 13:46:56) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyQt5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5'
>>>

**Comment by stuaxo** [comment]
I'd really recommend working in a separate virtualenv for this, since if you break vext python won't always start, which if you have a custom prompt might break that too.


What I do is have a folder `vext-projects` then in there clone vext and the other repos:

```
git clone https://github.com/vext-python/vext
git clone https://github.com/vext-python/vext.pyqt5.git
```

Then run `python setup.py install` in each directory to install vext and pyqt5.

If you make changes you will want to install again.

**Comment by Findus23** [comment]
I tested again a bit and it seems like the fix from https://github.com/vext-python/vext/pull/41 got lost at some time afterwards (maybe with https://github.com/vext-python/vext/commit/3ff1d3edbdbbdce537802a2a51a4cbe197928b92#diff-6c4bf655207051025745a4f0e21af3a3d69c17dd98a0a9dff28eee01e5f72e87).

I think no log level is set when debugging is not enabled and therefore warnings are shown.

This patch solves the issue for me:
```diff
diff --git a/vext/__init__.py b/vext/__init__.py
index 1858fa9..b83d0af 100644
--- a/vext/__init__.py
+++ b/vext/__init__.py
@@ -13,6 +13,7 @@ if VEXT_DEBUG_LOG in environ and environ.get(VEXT_DEBUG_LOG, "0") == "1":
     logger.setLevel(logging.DEBUG)
     logger.addHandler(logging.StreamHandler())
 else:
+    logger.setLevel(logging.ERROR)
     logger.addHandler(logging.NullHandler())
```

**Comment by stuaxo** [comment]
Look good to me, are you happy to make that a PR, along with a comment so it doesn't get removed ?
