### ISSUE TITLE
Deprecation of the distutils package

### ISSUE THREAD

**Issue by FriedrichFroebel** [stuaxo/vext#88]
The package still relies on the deprecated *distutils* package. There is some guidance available at https://peps.python.org/pep-0632/#migration-advice on how to migrate to alternatives.

* For `distutils.syconfig.get_python_lib`, `sysconfig.get_path("purelib")` seems like the correct replacement (https://github.com/pytorch/pytorch/commit/4b96fc060b0cb810965b5c8c08bc862a69965667): https://github.com/vext-python/vext/blob/9c0c6e1f193c556fabd77958b123f669be3dcfdd/vext/__init__.py#L5 https://github.com/vext-python/vext/blob/260f20726b258573e4d9fb9ea815d726431797c9/vext/env/__init__.py#L9 https://github.com/vext-python/vext/blob/9c0c6e1f193c556fabd77958b123f669be3dcfdd/vext/gatekeeper/__init__.py#L23
* For `distutils.version.StrictVersion`, `pkg_resources.parse_version` seems like the correct replacement (https://github.com/pypa/setuptools/discussions/3145): https://github.com/vext-python/vext/blob/9c0c6e1f193c556fabd77958b123f669be3dcfdd/setup.py#L10
* For `distutils.command.build.build`, `setuptools.command.build.build` seems like the correct replacement, although it is never used? https://github.com/vext-python/vext/blob/9c0c6e1f193c556fabd77958b123f669be3dcfdd/setup.py#L78

**Comment by stuaxo** [comment]
Good research, I tried all of these in a python shell and they seem like the right replacements, are you up for submitting a PR ?
