### ISSUE TITLE
"safe_load()" has been removed

### ISSUE THREAD

**Issue by titos-carrasco** [stuaxo/vext#92]
Please fix this error: "safe_load()" has been removed

Change line 22 in `__init__.py` from `data = yaml.safe_load(f)` to  `data = yaml.YAML(typ='safe', pure=True).load(f) `

**Comment by stuaxo** [comment]
That makes sense, can you submit a PR ?

**Comment by stuaxo** [comment]
https://github.com/vext-python/vext/pull/93

Merged a PR from @FriedrichFroebel with this.
